cd-cd fix : package local install

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -38,19 +38,18 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
 
-  tests:
-    name: Tests
+  test_232:
+    name: Tests(232)
     runs-on: ubuntu-latest
     needs: [style, doc-style]
     container:
-      image: ghcr.io/ansys/mechanical:24.1.0
+      image: ghcr.io/ansys/mechanical:23.2.0
       options: --entrypoint /bin/bash
     strategy:
       max-parallel: 2
       fail-fast: false
       matrix:
-        python-version: ['3.10']
-        #python-version: ['3.8', '3.9', '3.10', '3.11']
+        python-version: ['3.8', '3.9', '3.10', '3.11']
 
     steps:
       - uses: actions/checkout@v4
@@ -77,7 +76,7 @@ jobs:
         run: |
           pip3 install --upgrade pip
           pip3 install -r requirements/requirements_tests.txt
-
+          pip3 install .
       - name: Unit Testing and coverage
         run: |
           pytest > pytest_output.txt || true
@@ -85,7 +84,7 @@ jobs:
           #
           # Check if failure occurred
           #
-          output=$(grep -c "FAILURES" pytest_output.txt || true)
+          output=$(grep -c "ERROR" pytest_output.txt || true)
           if [ $output -eq 0 ]; then
             echo "Pytest execution succeeded"
             exit 0
@@ -98,13 +97,77 @@ jobs:
         uses: actions/upload-artifact@v3
         if: env.MAIN_PYTHON_VERSION == matrix.python-version
         with:
-          name: coverage-tests-remote-session-launch
+          name: coverage-tests-232
+          path: .cov
+          retention-days: 7
+
+  test_241:
+    name: Tests(241)
+    runs-on: ubuntu-latest
+    needs: [style, doc-style]
+    container:
+      image: ghcr.io/ansys/mechanical:24.1.0
+      options: --entrypoint /bin/bash
+    strategy:
+      max-parallel: 2
+      fail-fast: false
+      matrix:
+        python-version: ['3.8', '3.9', '3.10', '3.11']
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up python and pip
+        run: |
+          apt update
+          apt install software-properties-common -y
+          add-apt-repository ppa:deadsnakes/ppa -y
+          apt install python${{ matrix.python-version }} -y
+          ln -s /usr/bin/python${{ matrix.python-version }} /usr/bin/python
+          apt install python${{ matrix.python-version }}-venv -y
+
+      - name: Install pip
+        if: matrix.python-version == '3.8'
+        run: |
+          apt install -y python3-pip
+
+      - name: Install pip for >3.8
+        if: matrix.python-version != '3.8'
+        run: |
+          python -m ensurepip --default-pip
+
+      - name: Upgrade pip and install packages for testing
+        run: |
+          pip3 install --upgrade pip
+          pip3 install -r requirements/requirements_tests.txt
+          pip3 install .
+
+      - name: Unit Testing and coverage
+        run: |
+          pytest > pytest_output.txt || true
+          cat pytest_output.txt
+          #
+          # Check if failure occurred
+          #
+          output=$(grep -c "ERROR" pytest_output.txt || true)
+          if [ $output -eq 0 ]; then
+            echo "Pytest execution succeeded"
+            exit 0
+          else
+            echo "Pytest execution failed"
+            exit 1
+          fi
+
+      - name: Upload coverage results
+        uses: actions/upload-artifact@v3
+        if: env.MAIN_PYTHON_VERSION == matrix.python-version
+        with:
+          name: coverage-tests-242
           path: .cov
           retention-days: 7
 
   package:
     name: Package library
-    needs: [tests]
+    needs: [test_232, test_241]
     runs-on: ubuntu-latest
     steps:
       - name: Build library source and wheel artifacts
